### ISSUE TITLE
[Feature]: Treasury Support (Halt)

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#20]
### About

This is an alternative to VaultAPI but newer, good API and faster.

https://github.com/ArcanePlugins/Treasury/wiki/About-Treasury

https://github.com/ArcanePlugins/Treasury/wiki/Treasury's-Economy-API

**Comment by EncryptSL** [comment]
Maybe in future , i can include this api.

**Comment by LcyDev** [comment]
```
[23:11:45] [ForkJoinPool.commonPool-worker-1/ERROR]: [LiteEco] Exception executing command handler
kotlin.UninitializedPropertyAccessException: lateinit property econ has not been initialized
	at encryptsl.cekuj.net.LiteEco.getEcon(LiteEco.kt:36) ~[LiteEco-1.2.0-SNAPSHOT.jar:?]
	at encryptsl.cekuj.net.commands.MoneyCMD.onTopBalance(MoneyCMD.kt:95) ~[LiteEco-1.2.0-SNAPSHOT.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757) ~[?:?]
	at encryptsl.cekuj.net.cloud.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79) ~[LiteEco-1.2.0-SNAPSHOT.jar:?]
	at encryptsl.cekuj.net.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[LiteEco-1.2.0-SNAPSHOT.jar:?]
	at encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101) ~[LiteEco-1.2.0-SNAPSHOT.jar:?]
	at encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131) ~[LiteEco-1.2.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
It seems you forgot to initialize this variable. Used by onTopBalance()

**Comment by EncryptSL** [comment]
Its initialized but i missing rewrite format from Vault on own api.

https://github.com/EncryptSL/LiteEco/blob/main/src/main/kotlin/encryptsl/cekuj/net/commands/MoneyCMD.kt#L95

**Comment by EncryptSL** [comment]
Fixed

**Comment by MrIvanPlays** [comment]
Please do not add Treasury support until v2.0.0 gets released. v1 has many flaws with the API.

**Comment by EncryptSL** [comment]
Okay :)

**Comment by LcyDev** [comment]
```
20:00:20 ERROR]: Error occurred while enabling LiteEco v1.2.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: encryptsl/cekuj/net/api/economy/vault/AdaptiveEconomyVaultAPI
        at encryptsl.cekuj.net.LiteEco.hookRegistration(LiteEco.kt:137) ~[LiteEco-1.2.2-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.LiteEco.onEnable(LiteEco.kt:60) ~[LiteEco-1.2.2-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: encryptsl.cekuj.net.api.economy.vault.AdaptiveEconomyVaultAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more
```

I have no idea what's happening in this one

**Comment by LcyDev** [comment]
> Please do not add Treasury support until v2.0.0 gets released. v1 has many flaws with the API.

It seems v2.0.1 was released, time to re-implement with the new API.

**Comment by LcyDev** [comment]
I will try to make a pull request with this.
