### ISSUE TITLE
[Bug]: Cannot load from latest source code

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#26]
### What happened?

I don't really know what's happening here in the code it seems fine but it's just so you know it's there.

### Plugin Version

1.2.2-SNAP

### You detected problem on this server platform ?

PurpurMC

### Relevant log output

```cs
20:00:20 ERROR]: Error occurred while enabling LiteEco v1.2.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: encryptsl/cekuj/net/api/economy/vault/AdaptiveEconomyVaultAPI
        at encryptsl.cekuj.net.LiteEco.hookRegistration(LiteEco.kt:137) ~[LiteEco-1.2.2-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.LiteEco.onEnable(LiteEco.kt:60) ~[LiteEco-1.2.2-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: encryptsl.cekuj.net.api.economy.vault.AdaptiveEconomyVaultAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more
```

**Comment by EncryptSL** [comment]
Fixed in https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=486938.
