### ISSUE TITLE
[Bug]: Everything broke

### ISSUE THREAD

**Issue by Lemon553311-dev** [EncryptSL/LiteEco#44]
### What happened?

No commands are working. This happens 
This server is running Paper version git-Paper-423 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: fc072c0)

### Plugin Version

1.2.5-SNAPSHOT

### You detected problem on this server platform ?

PaperMC

### Relevant log output

```shell
[17:26:36 INFO]: Lemon553311 issued server command: /bal
[17:26:36 ERROR]: [LiteEco] Exception executing command handler
java.lang.NullPointerException: ofNullable(langConfigura….replace("<key>", value)) must not be null
        at encryptsl.cekuj.net.config.TranslationConfig.getMessage(TranslationConfig.kt:17) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.commands.MoneyCMD.onBalance(MoneyCMD.kt:53) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.commands.MoneyCMD.onBalanceProxy(MoneyCMD.kt:43) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757) ~[?:?]
        at encryptsl.cekuj.net.cloud.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131) ~[LiteEco-1.2.5-SNAPSHOT.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by EncryptSL** [comment]
Update your language file.

**Comment by Lemon553311-dev** [comment]
It didn't work
Trying to delete the language file does not bring it back.
I also tried downloading en_us local from here: https://github.com/EncryptSL/LiteEco/tree/main/src/main/resources/locale  and it didnt work..
Return the same error as before

**Comment by EncryptSL** [comment]
Main question is if you are doing this operation when is server off ? Or you are do hard reload ?

Bug not confirmed in version 1.2.5, tested on my side, with default downloaded plugin from spigot page.

Can you please post your en_us.yml in pastebin or use https://bytebin.lucko.me/

Please post full log. Without this i can't help you.
