### ISSUE TITLE
[Bug]:i tried to edit the messages and when i reloaded it didnt work

### ISSUE THREAD

**Issue by razvi030** [EncryptSL/LiteEco#50]
### What happened?

A bug happened!

### Plugin Version

latest

### You detected problem on this server platform ?

PurpurMC

### Relevant log output

```shell
[11:36:40 ERROR]: [LiteEco] Exception executing command handler
java.lang.IllegalAccessError: class encryptsl.cekuj.net.commands.MoneyCMD tried to access private field org.bukkit.plugin.java.JavaPlugin.logger (encryptsl.cekuj.net.commands.MoneyCMD is in unnamed module of loader 'LiteEco-1.3.2-SNAPSHOT.jar' @547d4bfd; org.bukkit.plugin.java.JavaPlugin is in unnamed module of loader java.net.URLClassLoader @5c29bfd)
at encryptsl.cekuj.net.commands.MoneyCMD.onReload(MoneyCMD.kt:383) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757) ~[?:?]
at encryptsl.cekuj.net.cloud.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
at encryptsl.cekuj.net.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
at encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
at encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by EncryptSL** [comment]
https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=499969

Solved by this update i gues.
