### ISSUE TITLE
Residence & LiteEco 

### ISSUE THREAD

**Issue by kvetinskystepan** [EncryptSL/LiteEco#6]
Hi, I have a question. I have a problem creating a residence and I get an error in the console: 

`at encryptsl.cekuj.net.api.AdaptiveEconomyProvider.has(AdaptiveEconomyProvider.kt:87) ~[LiteEco-1.1.3-SNAPSHOT.jar:?]
at encryptsl.cekuj.net.api.AdaptiveEconomyProvider.has(AdaptiveEconomyProvider.kt:87) ~[LiteEco-1.1.3-SNAPSHOT.jar:?]
at encryptsl.cekuj.net.api.AdaptiveEconomyProvider.has(AdaptiveEconomyProvider.kt:87) ~[LiteEco-1.1.3-SNAPSHOT.jar:?]`

Is it a problem residence or? Vault plugin is on the server.

With plugin JobsReborn it working nice.

**Comment by EncryptSL** [comment]
Error was printed after creating residence by player ?
