### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dinosrack** [EncryptSL/LiteEco#80]
### What happened?

Hi. I often see "this" in the console. What does this mean and can I turn off this endless spam?

### Plugin Version

1.4.4

### You detected problem on this server platform ?

PaperMC

### Version /version - output

```shell
[16:44:23 INFO]: Checking version, please wait...
[16:44:23 INFO]: This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-46 (MC: 1.20.4)
```

### Relevant log output

```shell
[16:36:07 WARN]: [CrazyAuctions] Task #677 for CrazyAuctions v1.3.2 generated an exception
java.lang.NullPointerException: null
    at com.github.encryptsl.lite.eco.common.hook.vault.AdaptiveEconomyVaultAPI.hasAccount(AdaptiveEconomyVaultAPI.kt:34) ~[LiteEco-1.4.4-SNAPSHOT.jar:?]
    at com.github.encryptsl.lite.eco.common.hook.vault.AdaptiveEconomyVaultAPI.getBalance(AdaptiveEconomyVaultAPI.kt:42) ~[LiteEco-1.4.4-SNAPSHOT.jar:?]
    at com.badbones69.crazyauctions.currency.VaultSupport.getMoney(VaultSupport.java:27) ~[CrazyAuctions-1.3.2.jar:?]
    at com.badbones69.crazyauctions.Methods.updateAuction(Methods.java:388) ~[CrazyAuctions-1.3.2.jar:?]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1653) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1532) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by EncryptSL** [comment]
Problem is not related to LiteEco,

In case: CrazyAuctions try call getMoney for online Player but when player logout player is offline and CrazyAuctions return null, 
In my case i can only add check for null.

**Comment by dinosrack** [comment]
![image](https://github.com/EncryptSL/LiteEco/assets/72701242/c286cd11-6380-423b-922f-e4a6fa016c19)

**Comment by dinosrack** [comment]
I don't understand what I need to do. The auctions worked and at some point stopped.

**Comment by EncryptSL** [comment]
Okay, i try you answer, my plugin works without any problems.
But weird is behaviour of CrazyAuctions.
Problem is when player leave server, CrazyAuctions try check getBalance but with required online Player on server... Idk why.

https://github.com/Crazy-Crew/CrazyAuctions/blob/main/paper/src/main/java/com/badbones69/crazyauctions/Methods.java#L249
https://github.com/Crazy-Crew/CrazyAuctions/blob/main/paper/src/main/java/com/badbones69/crazyauctions/Methods.java#L79

From my side i added check for null, but Crazy Auctions after check balance return items from seller like a expired because player is null in stage when leave server.

**Comment by dinosrack** [comment]
thank you <3
