### ISSUE TITLE
[Bug]: Release 1.4.8-SNAPSHOT Console Error

### ISSUE THREAD

**Issue by t4ba** [EncryptSL/LiteEco#86]
### What happened?

just installed snapshot on 1.21 purpur and plugin not getting enabled 

### Plugin Version

 1.4.8-SNAPSHOT

### You detected problem on this server platform ?

PurpurMC

### Version /version - output

```shell
[06:01:24 INFO]: Current Purpur Version: 1.21-2276-72ccfbd (MC: 1.21)*
* You are 8 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.20.6-2233-0d6766e (MC: 1.20.6)
```

### Relevant log output

```shell
[06:00:25 ERROR]: Error occurred while enabling LiteEco v1.4.8-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault2/economy/Economy
        at LiteEco-1.4.8-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.hook.HookManager.hookVault(HookManager.kt:67) ~[LiteEco-1.4.8-SNAPSHOT.jar:?]
        at LiteEco-1.4.8-SNAPSHOT.jar/com.github.encryptsl.lite.eco.LiteEco.hookRegistration(LiteEco.kt:102) ~[LiteEco-1.4.8-SNAPSHOT.jar:?]
        at LiteEco-1.4.8-SNAPSHOT.jar/com.github.encryptsl.lite.eco.LiteEco.onEnable(LiteEco.kt:77) ~[LiteEco-1.4.8-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault2.economy.Economy
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
```

**Comment by EncryptSL** [comment]
Fixed... Try this build i tested new build and error is not there.
https://github.com/EncryptSL/LiteEco/releases/tag/1.4.8.1-SNAPSHOT

**Comment by t4ba** [comment]
thanks new version works but my old players data not loading how can i keep the old data and use the new version of the plugin ?

**Comment by EncryptSL** [comment]
You have two options:

This is recommended and safe way.
1. If you are using mysql connection and you have PhpMyAdmin. 
2. You can export table lite_eco into lite_eco.sql.
3. Output from lite_eco.sql send there in pastebin or pastes.dev and i manually repair your data.


This is easier way but not tested.
Easier way can try use command eco migration LEGACY_TABLE

**Comment by t4ba** [comment]
> You have two options:
> 
> This is recommended and safe way.
> 
> 1. If you are using mysql connection and you have PhpMyAdmin.
> 2. You can export table lite_eco into lite_eco.sql.
> 3. Output from lite_eco.sql send there in pastebin or pastes.dev and i manually repair your data.
> 
> This is easier way but not tested. Easier way can try use command /eco migration LEGACY_TABLE

can move my current 1.4.7-SNAPSHOT db (sqlite) to mysql and use the recommended  method ?
